name: bloc_builder_generator
description: >-
  Code generator for Flutter BLoC pattern components including Cubit, BLoC, Event, 
  and State classes. Automatically generates type-safe boilerplate code from 
  reducing repetitive code and improving productivity.
version: 0.1.0
homepage: https://github.com/Myrkheimr/bloc_builder/tree/main/bloc_builder_generator
repository: https://github.com/Myrkheimr/bloc_builder
issue_tracker: https://github.com/Myrkheimr/bloc_builder/issues
publish_to: none

topics:
  - builder
  - build-runner
  - bloc
  - code-generation
  - codegen
  - flutter
  - dart

environment:
  sdk: ^3.9.0

dependencies:
  analyzer: ^8.1.1
  build: ^3.0.2
  build_config: ^1.2.0
  meta: ^1.17.0
  source_gen: ^3.1.0
  source_helper: ^1.3.7
  path: ^1.9.1
  bloc_annotation:
    path: ../bloc_annotation

dev_dependencies:
  lints: ^6.0.0
  build_runner: ^2.7.0
  build_verify: ^3.1.1
  source_gen_test: ^1.3.1
  test: ^1.25.6
  test_descriptor: ^2.0.2
  test_process: ^2.1.1
