name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  bloc: ^9.0.0
  bloc_builder_annotation:
    path: ../bloc_builder_annotation

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  build_runner: ^2.7.0
  bloc_test: ^10.0.0
  bloc_builder_generator:
    path: ../bloc_builder_generator
