name: bloc_annotation
description: Annotations for bloc_annotation code generation package
version: 1.0.0
homepage: https://github.com/Myrkheimr/bloc_annotation/tree/main/bloc_annotation
repository: https://github.com/Myrkheimr/bloc_annotation
issue_tracker: https://github.com/Myrkheimr/bloc_annotation/issues

topics:
  - annotation
  - bloc
  - code-generation
  - flutter
  - dart

environment:
  sdk: ^3.9.2

resolution: workspace
