name: bloc_annotation_generator
description: >-
  Code generator for Flutter BLoC pattern components including Cubit, BLoC, Event, 
  and State classes. Automatically generates type-safe boilerplate code.
version: 1.0.0
homepage: https://github.com/Myrkheimr/bloc_annotation/tree/main/bloc_annotation_generator
repository: https://github.com/Myrkheimr/bloc_annotation
issue_tracker: https://github.com/Myrkheimr/bloc_annotation/issues
publish_to: none

topics:
  - builder
  - build-runner
  - bloc
  - cubit
  - code-generation
  - codegen
  - flutter
  - dart

environment:
  sdk: ^3.9.2

resolution: workspace

dependencies:
  source_gen: ^3.1.0
  meta: ^1.17.0
  analyzer: ^8.1.1
  build: ^3.1.0
  build_config: ^1.2.0
  bloc_annotation: any

dev_dependencies:
  build_runner: ^2.7.1
  build_test: ^3.3.3
  build_verify: ^3.1.1
  lints: ^6.0.0
  source_gen_test: ^1.3.1
  test: ^1.25.6
